name: Node.js package

on:
  push:
    branches:
      - master
      - develop

jobs:

  publish-gpr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: '0'
          token: ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}

      - uses: actions/setup-node@master
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@hephaestus-technologies'

      - name: Bump Version and Push Tag
        id: bump_version
        uses: anothrNick/github-tag-action@1.26.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}
          WITH_V: true
          PRERELEASE_SUFFIX: dev

      - name: Build Project
        run: |
          npm install
          npm run build
          node scripts/bump-version.mjs
        env:
          version: ${{ steps.bump_version.outputs.new_tag }}
          NODE_AUTH_TOKEN: ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}

      - name: Publish Package
        run: npm publish build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}
